version: '3.8'

services:
  bloxchain:
    image: postgres:latest
    container_name: bloxchain
    restart: always
    environment:
      POSTGRES_DB: huay
      POSTGRES_USER: blox
      POSTGRES_PASSWORD: chain
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: